services:
  # Banco de dados PostgreSQL
  db:
    image: postgres:15
    container_name: db_postgres
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U petshop -d db_petshop"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Aplicação FastAPI
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: schedule_pet_shop_app
    restart: always
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data:
    driver: local