[project]
name = "schedule-pet-shop"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi[standard]>=0.115.11",
    "pylint>=3.3.4",
    "ruff>=0.9.9",
    "sqlmodel>=0.0.23",
]
